services:
    database:
        container_name: qabu-database
        image: postgres
        restart: no
        environment:
            POSTGRES_DB: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_NAME}
            PGUSER: ${POSTGRES_NAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10
    server:
        container_name: qabu
        restart: no
        environment:
            POSTGRES_URL: "postgresql://${POSTGRES_NAME}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_NAME}"
        build: 
            context: server
        ports:
            - "8080:8080"
        depends_on:
            database:
                condition: service_healthy
#   nginx:
#       container_name: qabu-nginx
#       image: nginx:1.23-alpine
#       ports:
#           - "80:80"
#       volumes:
#           - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
#       tty: true
#       depends_on:
#           - backend
#           - frontend
